# Generated by Django 3.2.14 on 2022-08-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_alter_generation_and_consumption_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='gas_supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('country', models.TextField(verbose_name='country')),
                ('gas_supply', models.FloatField(verbose_name='gas_supply')),
            ],
            options={
                'verbose_name': 'Объемы потребления газа',
                'verbose_name_plural': 'Объемы потребления газа',
            },
        ),
        migrations.DeleteModel(
            name='generation_and_consumption',
        ),
    ]
