# Generated by Django 3.2.14 on 2022-08-26 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consum_and_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generation_and_consumption',
            options={'verbose_name': 'Потребление газа с сайта eurostat', 'verbose_name_plural': 'Потребление газа с сайта eurostat'},
        ),
    ]
