# Generated by Django 3.2.14 on 2022-08-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash_RSV', '0003_prices_all'),
    ]

    operations = [
        migrations.CreateModel(
            name='gas_futures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='DT')),
                ('month_name', models.TextField(verbose_name='MONTH')),
                ('change_price', models.FloatField(verbose_name='CHANGE')),
                ('settle_price', models.FloatField(verbose_name='SETTLE')),
            ],
            options={
                'verbose_name': 'Цена фьючерсов на газ',
                'verbose_name_plural': 'Цена фьючерсов на газ',
            },
        ),
        migrations.DeleteModel(
            name='prices_all',
        ),
        migrations.DeleteModel(
            name='prices_RSV_from_ATS',
        ),
    ]
